<?php
declare(strict_types=1);

namespace Elone\Core;

use Elone\Core\Exception\HttpException;
use Elone\Core\Exception\UnsupportedParameterTypeException;
use Elone\Core\Routing\ControllerName;
use Elone\Core\Routing\Route;
use Elone\Core\Server\Request;
use Elone\Core\Server\Response;
use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;

readonly class Dispatcher
{
    /**
     * Dispatches a request to the appropriate controller/action, resolving method arguments and generating a response.
     *
     * @param \Elone\Core\Routing\Route $route The route containing information controller, action and parameters.
     * @param \Elone\Core\Server\Request $request The current HTTP request object.
     * @return \Elone\Core\Server\Response The HTTP response generated by the controller action or the rendered template.
     * @throws \ReflectionException If reflecting the controller's action fails.
     * @throws \Elone\Core\Exception\HttpException If a URL parameter can't be converted to the action's declared type.
     * @throws \Elone\Core\Exception\UnsupportedParameterTypeException If the action declares a parameter of a type
     * `resolveArguments()` doesn't know how to build from a URL segment.
     * @throws \Throwable Whatever the controller action itself throws, or whatever the template it renders throws.
     */
    public function dispatch(Route $route, Request $request): Response
    {
        $controllerClass = $route->controllerClass();

        $method = new ReflectionMethod($controllerClass, $route->action);

        $controller = new $controllerClass($request);

        $arguments = self::resolveArguments(method: $method, params: $route->params);

        $result = $method->invokeArgs($controller, $arguments);
        if ($result instanceof Response) {
            return $result;
        }

        $template = $this->templateName($route);
        $content = $controller->render($template);

        return new Response($content);
    }

    /**
     * @param list<string> $params
     * @return list<mixed>
     */
    protected static function resolveArguments(ReflectionMethod $method, array $params): array
    {
        $parameters = $method->getParameters();

        if (count($params) !== count($parameters)) {
            throw new HttpException(sprintf(
                'Invalid number of parameters for %s::%s(). Expected %d, received %d.',
                $method->getDeclaringClass()->getName(),
                $method->getName(),
                count($parameters),
                count($params),
            ));
        }

        $arguments = [];

        foreach ($parameters as $index => $parameter) {
            $arguments[] = self::convert(
                $params[$index],
                $parameter,
            );
        }

        return $arguments;
    }

    /**
     * Converts a string value to a specified type based on the provided parameter's type hint.
     *
     * @param string $value The string value to be converted.
     * @param \ReflectionParameter $parameter The reflection parameter containing type information for the conversion.
     * @return mixed The converted value, matching the parameter's type hint.
     * @throws \Elone\Core\Exception\HttpException If the conversion fails due to an invalid value matching a built-in type.
     * @throws \Elone\Core\Exception\UnsupportedParameterTypeException If the parameter's built-in type is not one this
     * method knows how to build from a URL segment.
     */
    private static function convert(string $value, ReflectionParameter $parameter): mixed
    {
        $type = $parameter->getType();
        if (!$type instanceof ReflectionNamedType || !$type->isBuiltin()) {
            return $value;
        }

        $typeName = $type->getName();

        if ($typeName === 'string') {
            return $value;
        }

        if ($typeName === 'int') {
            $converted = filter_var($value, FILTER_VALIDATE_INT, FILTER_NULL_ON_FAILURE);
            if ($converted === null) {
                throw new HttpException("Invalid integer parameter '$value' for `\${$parameter->getName()}`.");
            }

            return $converted;
        }

        if ($typeName === 'float') {
            $converted = filter_var($value, FILTER_VALIDATE_FLOAT, FILTER_NULL_ON_FAILURE);
            if ($converted === null) {
                throw new HttpException("Invalid float parameter '$value' for `\${$parameter->getName()}`.");
            }

            return $converted;
        }

        if ($typeName === 'bool') {
            $normalized = strtolower($value);
            if (in_array($normalized, ['1', 'true', 'yes'], true)) {
                return true;
            }

            if (in_array($normalized, ['0', 'false', 'no'], true)) {
                return false;
            }

            throw new HttpException("Invalid boolean parameter '$value' for `\${$parameter->getName()}`.");
        }

        throw new UnsupportedParameterTypeException(
            "Unsupported parameter type '$typeName' for `\${$parameter->getName()}`.",
        );
    }

    protected function templateName(Route $route): string
    {
        return new ControllerName($route->controller)->kebabCase() . "/$route->action";
    }
}
